#!/usr/bin/env bash
mkdir -p experiments/out-20min
for x in models/* ; do 
    folder_name=$(basename $x)
    mkdir -p experiments/out-20min/$folder_name
done
(python run-experiment.py omdt consensus-3-32 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/consensus-3-32/log-depth-1.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/consensus-3-32/log-depth-2.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/consensus-3-32/log-depth-3.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/consensus-3-32/log-depth-4.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/consensus-3-32/log-depth-5.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/consensus-3-32/log-depth-6.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/csma-2-4/log-depth-1.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/csma-2-4/log-depth-2.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/csma-2-4/log-depth-3.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/csma-2-4/log-depth-4.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/csma-2-4/log-depth-5.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/csma-2-4/log-depth-6.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/firewire-3/log-depth-1.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/firewire-3/log-depth-2.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/firewire-3/log-depth-3.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/firewire-3/log-depth-4.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/firewire-3/log-depth-5.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/firewire-3/log-depth-6.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/ij-10/log-depth-1.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/ij-10/log-depth-2.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/ij-10/log-depth-3.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/ij-10/log-depth-4.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/ij-10/log-depth-5.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/ij-10/log-depth-6.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/pnueli-zuck-3/log-depth-1.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/pnueli-zuck-3/log-depth-2.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/pnueli-zuck-3/log-depth-3.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/pnueli-zuck-3/log-depth-4.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/pnueli-zuck-3/log-depth-5.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/pnueli-zuck-3/log-depth-6.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/philosophers-4/log-depth-1.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/philosophers-4/log-depth-2.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/philosophers-4/log-depth-3.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/philosophers-4/log-depth-4.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/philosophers-4/log-depth-5.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/philosophers-4/log-depth-6.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/rabin-4/log-depth-1.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/rabin-4/log-depth-2.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/rabin-4/log-depth-3.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/rabin-4/log-depth-4.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/rabin-4/log-depth-5.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/rabin-4/log-depth-6.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/resource-gathering-5/log-depth-1.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/resource-gathering-5/log-depth-2.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/resource-gathering-5/log-depth-3.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/resource-gathering-5/log-depth-4.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/resource-gathering-5/log-depth-5.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/resource-gathering-5/log-depth-6.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 1 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/wlan-1-2/log-depth-1.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 2 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/wlan-1-2/log-depth-2.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 3 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/wlan-1-2/log-depth-3.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 4 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/wlan-1-2/log-depth-4.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 5 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/wlan-1-2/log-depth-5.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 6 --time_limit 1200 --output_dir experiments/out-20min/ --verbose 1 --model-file-name sketch-random-sink.drn) > experiments/out-20min/wlan-1-2/log-depth-6.log
