#!/usr/bin/env bash
experiment_name=01-21-omdt
timeout=1200
mkdir -p experiments/$experiment_name
for x in models/* ; do 
    folder_name=$(basename $x)
    mkdir -p experiments/$experiment_name/$folder_name
done
(python run-experiment.py omdt consensus-3-32 --seed 0 --gamma 0.9999 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/consensus-3-32/log-depth-1.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --gamma 0.9999 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/consensus-3-32/log-depth-2.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --gamma 0.9999 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/consensus-3-32/log-depth-3.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --gamma 0.9999 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/consensus-3-32/log-depth-4.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --gamma 0.9999 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/consensus-3-32/log-depth-5.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --gamma 0.9999 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/consensus-3-32/log-depth-6.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --gamma 0.9999 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/consensus-3-32/log-depth-7.log
(python run-experiment.py omdt consensus-3-32 --seed 0 --gamma 0.9999 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/consensus-3-32/log-depth-8.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/csma-2-4/log-depth-1.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/csma-2-4/log-depth-2.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/csma-2-4/log-depth-3.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/csma-2-4/log-depth-4.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/csma-2-4/log-depth-5.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/csma-2-4/log-depth-6.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/csma-2-4/log-depth-7.log
(python run-experiment.py omdt csma-2-4 --seed 0 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/csma-2-4/log-depth-8.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/firewire-3/log-depth-1.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/firewire-3/log-depth-2.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/firewire-3/log-depth-3.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/firewire-3/log-depth-4.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/firewire-3/log-depth-5.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/firewire-3/log-depth-6.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/firewire-3/log-depth-7.log
(python run-experiment.py omdt firewire-3 --seed 0 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/firewire-3/log-depth-8.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/ij-10/log-depth-1.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/ij-10/log-depth-2.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/ij-10/log-depth-3.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/ij-10/log-depth-4.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/ij-10/log-depth-5.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/ij-10/log-depth-6.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/ij-10/log-depth-7.log
(python run-experiment.py omdt ij-10 --seed 0 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/ij-10/log-depth-8.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/pnueli-zuck-3/log-depth-1.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/pnueli-zuck-3/log-depth-2.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/pnueli-zuck-3/log-depth-3.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/pnueli-zuck-3/log-depth-4.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/pnueli-zuck-3/log-depth-5.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/pnueli-zuck-3/log-depth-6.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/pnueli-zuck-3/log-depth-7.log
(python run-experiment.py omdt pnueli-zuck-3 --seed 0 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/pnueli-zuck-3/log-depth-8.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/philosophers-4/log-depth-1.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/philosophers-4/log-depth-2.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/philosophers-4/log-depth-3.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/philosophers-4/log-depth-4.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/philosophers-4/log-depth-5.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/philosophers-4/log-depth-6.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/philosophers-4/log-depth-7.log
(python run-experiment.py omdt philosophers-4 --seed 0 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/philosophers-4/log-depth-8.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/rabin-4/log-depth-1.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/rabin-4/log-depth-2.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/rabin-4/log-depth-3.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/rabin-4/log-depth-4.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/rabin-4/log-depth-5.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/rabin-4/log-depth-6.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/rabin-4/log-depth-7.log
(python run-experiment.py omdt rabin-4 --seed 0 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/rabin-4/log-depth-8.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/resource-gathering-5/log-depth-1.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/resource-gathering-5/log-depth-2.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/resource-gathering-5/log-depth-3.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/resource-gathering-5/log-depth-4.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/resource-gathering-5/log-depth-5.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/resource-gathering-5/log-depth-6.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/resource-gathering-5/log-depth-7.log
(python run-experiment.py omdt resource-gathering-5 --seed 0 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/resource-gathering-5/log-depth-8.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 1 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/wlan-1-2/log-depth-1.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 2 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/wlan-1-2/log-depth-2.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 3 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/wlan-1-2/log-depth-3.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 4 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/wlan-1-2/log-depth-4.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 5 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/wlan-1-2/log-depth-5.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 6 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/wlan-1-2/log-depth-6.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 7 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/wlan-1-2/log-depth-7.log
(python run-experiment.py omdt wlan-1-2 --seed 0 --max_depth 8 --time_limit $timeout --output_dir experiments/$experiment_name/ --verbose 1 --model-file-name model-random-enabled.drn) > experiments/$experiment_name/wlan-1-2/log-depth-8.log
